# Task 1

In [1]:
WIDTHS = [x for x in range(4, 33)]

In [3]:
checkpoint = "prajjwal1/bert-tiny"
tokenizer_checkpoint = "bert-base-uncased"
dataset_name = "imdb"

from transformers import AutoModelForSequenceClassification

from chop import MaseGraph
import chop.passes as passes

model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
model.config.problem_type = "single_label_classification"

mg = MaseGraph(
    model,
    hf_input_names=[
        "input_ids",
        "attention_mask",
        "labels",
    ],
)

mg, _ = passes.init_metadata_analysis_pass(mg)
mg, _ = passes.add_common_metadata_analysis_pass(mg)

from chop.tools import get_tokenized_dataset, get_trainer

dataset, tokenizer = get_tokenized_dataset(
    dataset=dataset_name,
    checkpoint=tokenizer_checkpoint,
    return_tokenizer=True,
)



from pathlib import Path
from chop import MaseGraph

mg = MaseGraph.from_checkpoint("../saves/tutorial_2_lora")

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at prajjwal1/bert-tiny and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
`past_key_values` were not specified as input names, but model.config.use_cache = True. Setting model.config.use_cache = False.
INFO     Getting dummy input for prajjwal1/bert-tiny.

tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
tensor([[ 101, 9932, 2089, 2202, 2058, 1996, 2088, 2028, 2154,  102],
        [ 101, 2023, 2003, 2339, 2017, 2323, 4553, 4748, 4877,  102]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]]])
tensor([[[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]])
tensor([[[ 0.7973,  0.0109, -8.8405,  ...,  1.4170,  0.1046, -0.1551],
         [-1.1766,  1.2879, -1.0986,  ...,  0.4749, -0.5899,  0.8746],
         [-2.0560,  0.7748, -0.8909,  ..., -0.4034,  0.5352, -1.3657],
         ...,
         [ 0.2317, -0.7896,  0.9634,  ..., -0.8037,  0.4834, -0.5868],
         [ 0.0243, -1.0235, -1.2771,  ..., -2.2378,  1.8530,  0.1558],
         [-1.3637,  0.7055, -0.2177,  ...,  0.3557, -0.3971, -0.3107]],

        [[ 0.7973,  0.0109, -8.8405,  ...,  1.4170,  0.1046, -0.1551],
         [-2.6940,  0.6198, -0.4564,  ..., -1.4367, -1.5705, -3.1260],
         [-1.7524,  0.8535, -0.2155,  ..., -0.5222, -1.2430, -1.7199],
         ...,
         [-0.0347,  0.7446,  1.4462,  ..., -1.1578, -2.6197,  0.2612],
         [ 2.4334, -0.3068,  0.8250,  ...,  0.1475,  0.1790,  2.2907],
         [-1.3637,  0.7055, -0.2177,  ...,  0.3557, -0.3971, -0.3107]]],
       grad_fn=<NativeLayerNormBackward0>)
tensor([[[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ...,  1.4757e-01,
           1.8900e-01,  2.8282e-01],
         [-3.5020e-02, -6.1047e-02, -1.0465e-01,  ..., -8.1892e-01,
           1.1978e+00,  2.1808e+00],
         [ 4.3982e-01, -1.9602e+00, -6.8830e-01,  ..., -6.3025e-01,
          -1.5967e-01,  1.3284e+00],
         ...,
         [ 1.4783e+00,  1.0907e-01, -1.5222e+00,  ..., -3.0983e-01,
          -1.2971e-01,  1.1265e+00],
         [ 1.5890e+00, -1.6859e+00,  7.8703e-01,  ..., -1.3174e+00,
           2.2258e-01,  8.8157e-01],
         [-3.7517e-01,  1.5191e+00, -2.6796e-01,  ..., -1.6159e+00,
           7.2677e-02,  1.1724e-01]],

        [[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ...,  1.4757e-01,
           1.8900e-01,  2.8282e-01],
         [-4.4781e-01, -7.9224e-01, -2.1741e+00,  ..., -5.9181e-01,
           1.4373e+00,  2.4267e+00],
         [-2.5942e-01,  9.7163e-01, -3.2928e+00,  ..., -5.9773e-01,
          -3.0482e-01,  1.4038e+00],
         ...,
         [ 5.1575e-02,  3.5218e-01, -3.8926e-01,  ..., -1.1508e+00,
           7.5490e-01,  8.2911e-01],
         [ 1.6107e+00,  6.8170e-02,  9.2537e-01,  ..., -1.5233e+00,
          -6.0733e-01,  3.3097e-01],
         [-3.7517e-01,  1.5191e+00, -2.6796e-01,  ..., -1.6159e+00,
           7.2677e-02,  1.1724e-01]]], grad_fn=<ViewBackward0>)
tensor([[[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ...,  1.4757e-01,
           1.8900e-01,  2.8282e-01],
         [-3.5020e-02, -6.1047e-02, -1.0465e-01,  ..., -8.1892e-01,
           1.1978e+00,  2.1808e+00],
         [ 4.3982e-01, -1.9602e+00, -6.8830e-01,  ..., -6.3025e-01,
          -1.5967e-01,  1.3284e+00],
         ...,
         [ 1.4783e+00,  1.0907e-01, -1.5222e+00,  ..., -3.0983e-01,
          -1.2971e-01,  1.1265e+00],
         [ 1.5890e+00, -1.6859e+00,  7.8703e-01,  ..., -1.3174e+00,
           2.2258e-01,  8.8157e-01],
         [-3.7517e-01,  1.5191e+00, -2.6796e-01,  ..., -1.6159e+00,
           7.2677e-02,  1.1724e-01]],

        [[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ...,  1.4757e-01,
           1.8900e-01,  2.8282e-01],
         [-4.4781e-01, -7.9224e-01, -2.1741e+00,  ..., -5.9181e-01,
           1.4373e+00,  2.4267e+00],
         [-2.5942e-01,  9.7163e-01, -3.2928e+00,  ..., -5.9773e-01,
          -3.0482e-01,  1.4038e+00],
         ...,
         [ 5.1575e-02,  3.5218e-01, -3.8926e-01,  ..., -1.1508e+00,
           7.5490e-01,  8.2911e-01],
         [ 1.6107e+00,  6.8170e-02,  9.2537e-01,  ..., -1.5233e+00,
          -6.0733e-01,  3.3097e-01],
         [-3.7517e-01,  1.5191e+00, -2.6796e-01,  ..., -1.6159e+00,
           7.2677e-02,  1.1724e-01]]], grad_fn=<ViewBackward0>)
tensor([[[[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ..., -5.2614e-01,
           -3.5687e-01, -2.6793e-01],
          [ 2.0335e-01, -5.4534e-01,  3.0686e-01,  ...,  1.4757e-01,
            1.8900e-01,  2.8282e-01]],

         [[-3.5020e-02, -6.1047e-02, -1.0465e-01,  ..., -2.0138e+00,
            4.5529e-01, -7.8171e-01],
          [ 1.1969e+00,  1.6337e+00,  2.5047e-01,  ..., -8.1892e-01,
            1.1978e+00,  2.1808e+00]],

         [[ 4.3982e-01, -1.9602e+00, -6.8830e-01,  ..., -2.2501e-01,
            7.2290e-02, -1.8290e+00],
          [ 8.9952e-01,  1.0029e+00,  7.4536e-04,  ..., -6.3025e-01,
           -1.5967e-01,  1.3284e+00]],

         ...,

         [[ 1.4783e+00,  1.0907e-01, -1.5222e+00,  ...,  1.1867e+00,
           -1.3561e+00,  6.5158e-01],
          [ 9.5466e-01,  4.5887e-01,  7.8078e-01,  ..., -3.0983e-01,
           -1.2971e-01,  1.1265e+00]],

         [[ 1.5890e+00, -1.6859e+00,  7.8703e-01,  ...,  6.5467e-01,
           -6.8451e-01,  6.5081e-01],
          [ 7.0729e-01,  1.4499e+00, -1.5089e-01,  ..., -1.3174e+00,
            2.2258e-01,  8.8157e-01]],

         [[-3.7517e-01,  1.5191e+00, -2.6796e-01,  ...,  3.3130e-01,
           -3.2756e-01, -6.3130e-01],
          [ 8.6773e-01,  2.0996e-01, -3.4332e-01,  ..., -1.6159e+00,
            7.2677e-02,  1.1724e-01]]],


        [[[ 9.7740e-01,  2.5482e-03, -5.2921e-01,  ..., -5.2614e-01,
           -3.5687e-01, -2.6793e-01],
          [ 2.0335e-01, -5.4534e-01,  3.0686e-01,  ...,  1.4757e-01,
            1.8900e-01,  2.8282e-01]],

         [[-4.4781e-01, -7.9224e-01, -2.1741e+00,  ...,  1.7508e+00,
           -3.6708e-01, -1.3251e+00],
          [ 7.9208e-01, -1.3537e-01,  2.3756e-01,  ..., -5.9181e-01,
            1.4373e+00,  2.4267e+00]],

         [[-2.5942e-01,  9.7163e-01, -3.2928e+00,  ..., -9.6646e-01,
           -4.8876e-01, -1.4426e+00],
          [ 1.0250e+00, -6.9093e-01, -1.2734e+00,  ..., -5.9773e-01,
           -3.0482e-01,  1.4038e+00]],

         ...,

         [[ 5.1575e-02,  3.5218e-01, -3.8926e-01,  ..., -1.2252e-02,
            1.0394e+00,  4.2402e-01],
          [-4.7386e-01,  2.6401e+00,  1.7024e+00,  ..., -1.1508e+00,
            7.5490e-01,  8.2911e-01]],

         [[ 1.6107e+00,  6.8170e-02,  9.2537e-01,  ..., -6.1665e-01,
            2.7627e-01, -1.2083e+00],
          [ 9.3395e-01, -9.7541e-01, -2.5442e-02,  ..., -1.5233e+00,
           -6.0733e-01,  3.3097e-01]],

         [[-3.7517e-01,  1.5191e+00, -2.6796e-01,  ...,  3.3130e-01,
           -3.2756e-01, -6.3130e-01],
          [ 8.6773e-01,  2.0996e-01, -3.4332e-01,  ..., -1.6159e+00,
            7.2677e-02,  1.1724e-01]]]], grad_fn=<ViewBackward0>)
tensor([[[-0.1709,  0.5230, -0.8713,  ..., -1.3382,  0.5892,  0.4026],
         [-0.5842,  0.9588,  1.5642,  ..., -1.0731, -0.7330,  0.3132],
         [-0.8601, -1.3756,  0.5042,  ..., -0.0476,  0.2650,  1.2150],
         ...,
         [ 0.0520,  1.1719, -1.5471,  ..., -0.7894,  0.1419,  1.6964],
         [ 0.7654, -1.5053, -0.4142,  ..., -1.4622, -0.8975,  1.4576],
         [-1.2008, -0.6008, -1.4608,  ..., -1.2105, -0.4289,  0.3827]],

        [[-0.1709,  0.5230, -0.8713,  ..., -1.3382,  0.5892,  0.4026],
         [-1.3806,  0.2626, -0.5207,  ..., -1.6714, -0.0554,  1.0225],
         [-1.7116,  1.8788, -2.5695,  ..., -0.6958,  0.5728,  0.5461],
         ...,
         [-1.3246,  1.2196, -0.3034,  ..., -1.1955, -0.6708,  0.5128],
         [ 0.9854,  0.8260,  0.2892,  ..., -0.6428,  0.3637,  0.4339],
         [-1.2008, -0.6008, -1.4608,  ..., -1.2105, -0.4289,  0.3827]]],
       grad_fn=<ViewBackward0>)
tensor([[[-0.1709,  0.5230, -0.8713,  ..., -1.3382,  0.5892,  0.4026],
         [-0.5842,  0.9588,  1.5642,  ..., -1.0731, -0.7330,  0.3132],
         [-0.8601, -1.3756,  0.5042,  ..., -0.0476,  0.2650,  1.2150],
         ...,
         [ 0.0520,  1.1719, -1.5471,  ..., -0.7894,  0.1419,  1.6964],
         [ 0.7654, -1.5053, -0.4142,  ..., -1.4622, -0.8975,  1.4576],
         [-1.2008, -0.6008, -1.4608,  ..., -1.2105, -0.4289,  0.3827]],

        [[-0.1709,  0.5230, -0.8713,  ..., -1.3382,  0.5892,  0.4026],
         [-1.3806,  0.2626, -0.5207,  ..., -1.6714, -0.0554,  1.0225],
         [-1.7116,  1.8788, -2.5695,  ..., -0.6958,  0.5728,  0.5461],
         ...,
         [-1.3246,  1.2196, -0.3034,  ..., -1.1955, -0.6708,  0.5128],
         [ 0.9854,  0.8260,  0.2892,  ..., -0.6428,  0.3637,  0.4339],
         [-1.2008, -0.6008, -1.4608,  ..., -1.2105, -0.4289,  0.3827]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.1709,  0.5230, -0.8713,  ...,  0.4365,  0.6238, -0.9414],
          [-1.3731,  1.1521,  0.1321,  ..., -1.3382,  0.5892,  0.4026]],

         [[-0.5842,  0.9588,  1.5642,  ..., -1.5431,  0.4999, -1.1350],
          [ 0.9615,  0.8694,  0.0998,  ..., -1.0731, -0.7330,  0.3132]],

         [[-0.8601, -1.3756,  0.5042,  ...,  0.9764, -0.8321, -1.0204],
          [ 1.5175,  1.1454,  0.7791,  ..., -0.0476,  0.2650,  1.2150]],

         ...,

         [[ 0.0520,  1.1719, -1.5471,  ...,  1.9402, -1.1294,  0.4793],
          [ 1.0053,  0.8099,  1.6415,  ..., -0.7894,  0.1419,  1.6964]],

         [[ 0.7654, -1.5053, -0.4142,  ...,  1.7455, -0.7326,  1.5248],
          [ 1.0806,  1.1457,  2.2163,  ..., -1.4622, -0.8975,  1.4576]],

         [[-1.2008, -0.6008, -1.4608,  ...,  2.0905,  1.8849, -1.5708],
          [ 1.9999,  0.3493, -0.8524,  ..., -1.2105, -0.4289,  0.3827]]],


        [[[-0.1709,  0.5230, -0.8713,  ...,  0.4365,  0.6238, -0.9414],
          [-1.3731,  1.1521,  0.1321,  ..., -1.3382,  0.5892,  0.4026]],

         [[-1.3806,  0.2626, -0.5207,  ...,  1.6517, -0.2316, -1.3171],
          [ 0.6812, -0.0090,  0.3803,  ..., -1.6714, -0.0554,  1.0225]],

         [[-1.7116,  1.8788, -2.5695,  ...,  0.4927, -0.4850, -1.0645],
          [ 1.2646,  1.6481,  0.9055,  ..., -0.6958,  0.5728,  0.5461]],

         ...,

         [[-1.3246,  1.2196, -0.3034,  ...,  1.2747,  1.2353,  0.2825],
          [ 1.5373,  0.8648,  0.6062,  ..., -1.1955, -0.6708,  0.5128]],

         [[ 0.9854,  0.8260,  0.2892,  ...,  1.3848, -0.0103, -1.0700],
          [ 1.3827,  2.9809,  0.0276,  ..., -0.6428,  0.3637,  0.4339]],

         [[-1.2008, -0.6008, -1.4608,  ...,  2.0905,  1.8849, -1.5708],
          [ 1.9999,  0.3493, -0.8524,  ..., -1.2105, -0.4289,  0.3827]]]],
       grad_fn=<ViewBackward0>)
tensor([[[-0.0123,  0.5761,  0.2209,  ..., -0.1027,  1.1061, -2.5200],
         [-1.1465, -1.5578, -0.6984,  ...,  1.0310,  0.4824, -0.2291],
         [-1.0361, -1.8192, -2.3055,  ...,  1.5286, -1.5941,  1.1762],
         ...,
         [-0.7992,  0.0886,  0.4887,  ..., -1.7941,  0.4835,  1.3780],
         [-1.4692, -0.9135, -0.2802,  ..., -0.9691,  0.3500,  1.8863],
         [-0.5760, -0.0452,  0.4230,  ..., -0.7179, -0.7858,  1.6879]],

        [[-0.0123,  0.5761,  0.2209,  ..., -0.1027,  1.1061, -2.5200],
         [-0.3700, -1.9754, -0.7315,  ...,  0.2293,  0.6996,  3.1299],
         [-0.6252,  0.2879, -1.4036,  ..., -2.0560, -2.4623, -0.9584],
         ...,
         [-1.1306, -1.4343, -1.4422,  ..., -1.6115, -0.0475,  1.3975],
         [-0.9816, -1.4909, -1.0086,  ..., -0.9284,  0.5260,  1.5330],
         [-0.5760, -0.0452,  0.4230,  ..., -0.7179, -0.7858,  1.6879]]],
       grad_fn=<ViewBackward0>)
tensor([[[-0.0123,  0.5761,  0.2209,  ..., -0.1027,  1.1061, -2.5200],
         [-1.1465, -1.5578, -0.6984,  ...,  1.0310,  0.4824, -0.2291],
         [-1.0361, -1.8192, -2.3055,  ...,  1.5286, -1.5941,  1.1762],
         ...,
         [-0.7992,  0.0886,  0.4887,  ..., -1.7941,  0.4835,  1.3780],
         [-1.4692, -0.9135, -0.2802,  ..., -0.9691,  0.3500,  1.8863],
         [-0.5760, -0.0452,  0.4230,  ..., -0.7179, -0.7858,  1.6879]],

        [[-0.0123,  0.5761,  0.2209,  ..., -0.1027,  1.1061, -2.5200],
         [-0.3700, -1.9754, -0.7315,  ...,  0.2293,  0.6996,  3.1299],
         [-0.6252,  0.2879, -1.4036,  ..., -2.0560, -2.4623, -0.9584],
         ...,
         [-1.1306, -1.4343, -1.4422,  ..., -1.6115, -0.0475,  1.3975],
         [-0.9816, -1.4909, -1.0086,  ..., -0.9284,  0.5260,  1.5330],
         [-0.5760, -0.0452,  0.4230,  ..., -0.7179, -0.7858,  1.6879]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.0123,  0.5761,  0.2209,  ..., -0.1457, -0.7538,  0.1761],
          [-0.0705,  0.9215,  0.7990,  ..., -0.1027,  1.1061, -2.5200]],

         [[-1.1465, -1.5578, -0.6984,  ...,  0.0289, -2.1112, -0.8728],
          [ 0.6506, -1.6966,  1.4463,  ...,  1.0310,  0.4824, -0.2291]],

         [[-1.0361, -1.8192, -2.3055,  ..., -0.2195, -1.1732,  0.3182],
          [-0.5841, -0.0227,  3.0901,  ...,  1.5286, -1.5941,  1.1762]],

         ...,

         [[-0.7992,  0.0886,  0.4887,  ...,  0.7859, -1.0127, -0.2676],
          [-0.3055,  0.6270, -3.0705,  ..., -1.7941,  0.4835,  1.3780]],

         [[-1.4692, -0.9135, -0.2802,  ...,  0.1197, -0.7532,  0.0731],
          [ 0.6096, -1.0893, -0.6959,  ..., -0.9691,  0.3500,  1.8863]],

         [[-0.5760, -0.0452,  0.4230,  ...,  0.8851,  0.3078,  0.8106],
          [-1.1804,  0.9512,  0.3169,  ..., -0.7179, -0.7858,  1.6879]]],


        [[[-0.0123,  0.5761,  0.2209,  ..., -0.1457, -0.7538,  0.1761],
          [-0.0705,  0.9215,  0.7990,  ..., -0.1027,  1.1061, -2.5200]],

         [[-0.3700, -1.9754, -0.7315,  ...,  0.5756, -1.5559,  0.0326],
          [ 1.4229,  2.3970, -0.4516,  ...,  0.2293,  0.6996,  3.1299]],

         [[-0.6252,  0.2879, -1.4036,  ...,  0.5306, -0.5608,  1.1861],
          [-2.5980,  0.2673,  3.3016,  ..., -2.0560, -2.4623, -0.9584]],

         ...,

         [[-1.1306, -1.4343, -1.4422,  ...,  0.3918, -1.5336, -0.5026],
          [ 1.8587,  0.8501, -1.2402,  ..., -1.6115, -0.0475,  1.3975]],

         [[-0.9816, -1.4909, -1.0086,  ...,  0.2956,  0.0351, -1.0685],
          [-0.6594, -0.0133, -1.1863,  ..., -0.9284,  0.5260,  1.5330]],

         [[-0.5760, -0.0452,  0.4230,  ...,  0.8851,  0.3078,  0.8106],
          [-1.1804,  0.9512,  0.3169,  ..., -0.7179, -0.7858,  1.6879]]]],
       grad_fn=<ViewBackward0>)
tensor([[[[-0.5911, -0.4682, -0.4314,  ...,  0.0366, -1.0405, -0.0579],
          [-1.1141, -1.4785, -0.6477,  ...,  0.0631, -1.9950, -0.7912],
          [-0.7059, -0.9954, -1.3923,  ..., -0.1557, -0.9998,  0.2774],
          ...,
          [-0.6300,  0.1252,  0.3486,  ...,  0.5692, -0.9417, -0.1399],
          [-1.0593, -0.6395, -0.3343,  ...,  0.0571, -0.7842,  0.1042],
          [-0.2081,  0.2785,  0.0613,  ..., -0.0353, -0.8389, -0.0026]],

         [[-0.3266,  0.6360,  0.0214,  ...,  0.1677,  0.3883,  0.4382],
          [-0.6299,  0.6012,  0.7379,  ...,  0.2989, -0.1569,  0.9508],
          [-0.4097,  0.6374, -0.1589,  ...,  0.0258, -0.0364,  0.9990],
          ...,
          [-0.0088,  0.1378, -0.4819,  ..., -0.1261,  0.2908,  1.0980],
          [-0.5584,  0.9932, -0.1105,  ...,  0.2486,  0.4005,  0.6046],
          [-0.4516,  0.8092, -0.0513,  ...,  0.1182,  0.4294,  0.4781]]],


        [[[-0.6850, -0.2168, -0.6087,  ...,  0.1402, -0.7267, -0.1502],
          [-0.2084, -0.1325, -0.1151,  ...,  0.0938, -0.8963,  0.1296],
          [-0.3665,  0.3408, -0.6133,  ...,  0.1938, -0.6681,  0.5929],
          ...,
          [-1.0985, -1.2861, -1.2531,  ...,  0.3609, -1.4022, -0.4444],
          [-0.9787, -1.4207, -0.9908,  ...,  0.2989, -0.0159, -1.0060],
          [-0.1970,  0.2371, -0.0115,  ...,  0.0049, -0.8135,  0.1201]],

         [[ 0.0907,  0.7927, -0.0524,  ..., -0.4610, -0.4295,  0.4391],
          [-0.2352,  1.0586, -0.1117,  ..., -0.4943, -0.6546,  0.6617],
          [ 0.8269,  1.7861, -1.1207,  ..., -0.0885,  0.2791,  1.4721],
          ...,
          [-0.1038,  0.9623, -0.7062,  ..., -0.3340, -0.3050,  0.8792],
          [ 0.0507,  0.6634, -0.2642,  ..., -0.4959, -0.7944,  0.7687],
          [ 0.3364,  0.9047, -0.2037,  ..., -0.3705, -0.2893,  0.6787]]]],
       grad_fn=<ScaledDotProductFlashAttentionForCpuBackward0>)
tensor([[[[-0.5911, -0.4682, -0.4314,  ...,  0.0366, -1.0405, -0.0579],
          [-0.3266,  0.6360,  0.0214,  ...,  0.1677,  0.3883,  0.4382]],

         [[-1.1141, -1.4785, -0.6477,  ...,  0.0631, -1.9950, -0.7912],
          [-0.6299,  0.6012,  0.7379,  ...,  0.2989, -0.1569,  0.9508]],

         [[-0.7059, -0.9954, -1.3923,  ..., -0.1557, -0.9998,  0.2774],
          [-0.4097,  0.6374, -0.1589,  ...,  0.0258, -0.0364,  0.9990]],

         ...,

         [[-0.6300,  0.1252,  0.3486,  ...,  0.5692, -0.9417, -0.1399],
          [-0.0088,  0.1378, -0.4819,  ..., -0.1261,  0.2908,  1.0980]],

         [[-1.0593, -0.6395, -0.3343,  ...,  0.0571, -0.7842,  0.1042],
          [-0.5584,  0.9932, -0.1105,  ...,  0.2486,  0.4005,  0.6046]],

         [[-0.2081,  0.2785,  0.0613,  ..., -0.0353, -0.8389, -0.0026],
          [-0.4516,  0.8092, -0.0513,  ...,  0.1182,  0.4294,  0.4781]]],


        [[[-0.6850, -0.2168, -0.6087,  ...,  0.1402, -0.7267, -0.1502],

INFO     Tokenizing dataset imdb with AutoTokenizer for bert-base-uncased.
WARNING  Node finfo not found in loaded metadata.
WARNING  Node getattr_2 not found in loaded metadata.

## PTQ Iterations

In [4]:
import chop.passes as passes

def get_quantisation_config(width):
    quantization_config = {
        "by": "type",
        "default": {
            "config": {
                "name": None,
            }
        },
        "linear": {
            "config": {
                "name": "integer",
                # data
                "data_in_width": width,
                "data_in_frac_width": width//2,
                # weight
                "weight_width": width,
                "weight_frac_width": width//2,
                # bias
                "bias_width": width,
                "bias_frac_width": width//2,
            }
        },
    }
    return quantization_config

In [ ]:


ptq_accuracies = []

for width in WIDTHS:
    mg, _ = passes.quantize_transform_pass(mg,pass_args=get_quantisation_config(width),)
    trainer = get_trainer(
        model=mg.model,
        tokenized_dataset=dataset,
        tokenizer=tokenizer,
        evaluate_metric="accuracy",
    )
    eval_results = trainer.evaluate()
    print(f"Evaluation accuracy: {eval_results['eval_accuracy']}, Bit Width: {width}")
    ptq_accuracies.append(eval_results['eval_accuracy'])

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.5, Bit Width: 4

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.5, Bit Width: 5

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.69216, Bit Width: 6

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.69152, Bit Width: 7

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.80836, Bit Width: 8

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.81224, Bit Width: 9

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.82404, Bit Width: 10

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.82404, Bit Width: 11

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83696, Bit Width: 12

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83696, Bit Width: 13

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83632, Bit Width: 14

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83632, Bit Width: 15

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83736, Bit Width: 16

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83736, Bit Width: 17

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83788, Bit Width: 18

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83788, Bit Width: 19

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83788, Bit Width: 20

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83788, Bit Width: 21

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83772, Bit Width: 22

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83772, Bit Width: 23

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83764, Bit Width: 24

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83764, Bit Width: 25

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83776, Bit Width: 26

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83776, Bit Width: 27

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83772, Bit Width: 28

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83772, Bit Width: 29

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83776, Bit Width: 30

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83776, Bit Width: 31

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.83772, Bit Width: 32

In [ ]:
print(ptq_accuracies)

[0.5, 0.5, 0.69216, 0.69152, 0.80836, 0.81224, 0.82404, 0.82404, 0.83696, 0.83696, 0.83632, 0.83632, 0.83736, 0.83736, 0.83788, 0.83788, 0.83788, 0.83788, 0.83772, 0.83772, 0.83764, 0.83764, 0.83776, 0.83776, 0.83772, 0.83772, 0.83776, 0.83776, 0.83772]

## QAT Iterations

In [ ]:
qat_accuracies = []

for width in WIDTHS:
    mg, _ = passes.quantize_transform_pass(mg,pass_args=get_quantisation_config(width),)
    trainer = get_trainer(
        model=mg.model,
        tokenized_dataset=dataset,
        tokenizer=tokenizer,
        evaluate_metric="accuracy",
    )
    trainer.train()
    eval_results = trainer.evaluate()
    print(f"Evaluation accuracy: {eval_results['eval_accuracy']}, Bit Width: {width}")
    qat_accuracies.append(eval_results['eval_accuracy'])

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

KeyboardInterrupt:

In [ ]:
print(qat_accuracies)

[0.5, 0.5, 0.83392, 0.83064, 0.84184, 0.84228, 0.84416, 0.84452, 0.84508, 0.84556, 0.84584, 0.84576, 0.84612, 0.846, 0.84544, 0.84548, 0.84596, 0.84592, 0.84596, 0.84588, 0.8458, 0.8458, 0.84584, 0.84584, 0.84608, 0.84612, 0.84596, 0.84596, 0.84604]

In [ ]:
# Find best model

qat_accuracies = [0.5, 0.5, 0.83392, 0.83064, 0.84184, 0.84228, 0.84416, 0.84452, 0.84508, 0.84556, 0.84584, 0.84576, 0.84612, 0.846, 0.84544, 0.84548, 0.84596, 0.84592, 0.84596, 0.84588, 0.8458, 0.8458, 0.84584, 0.84584, 0.84608, 0.84612, 0.84596, 0.84596, 0.84604]
ptq_accuracies = [0.5, 0.5, 0.69216, 0.69148, 0.80836, 0.81224, 0.82404, 0.82404, 0.83684, 0.83684, 0.83628, 0.83628, 0.83732, 0.83732, 0.83792, 0.83792, 0.83788, 0.83788, 0.83772, 0.83772, 0.83764, 0.83764, 0.8378, 0.8378, 0.83772, 0.83772, 0.83776, 0.83776, 0.83772]

best_PTQ = 0
best_PTQ_width = 0;
best_QAT = 0
best_QAT_width = 0;



for i in range(len(WIDTHS)):
    if ptq_accuracies[i] > best_PTQ:
        best_PTQ_width = WIDTHS[i]
    if qat_accuracies[i] > best_QAT:
        best_QAT_width = WIDTHS[i]
print(best_PTQ_width, best_QAT_width)

32 32

# Task 2

In [5]:
# PTQ 32 bit width
import numpy as np


SPARSITIES = np.arange(0.1, 1, 0.1)
pruned_accuracies = {"l1-norm": [],
                     "random" : []}
def get_pruning_config(sparsity, mode):
    pruning_config = {
        "weight": {
            "sparsity": 0.5,
            "method": mode,
            "scope": "local",
        },
        "activation": {
            "sparsity": 0.5,
            "method": mode,
            "scope": "local",
        },
    }
    return pruning_config

In [ ]:


for mode in ["l1-norm", "random"]:
    for sparsity in SPARSITIES:
        mg, _ = passes.quantize_transform_pass(mg,pass_args=get_quantisation_config(32),)
        mg.model.to("cuda:0")
        mg, _ = passes.prune_transform_pass(mg, pass_args=get_pruning_config(sparsity, mode))
        mg.model.to("cuda:0")
        trainer = get_trainer(
            model=mg.model,
            tokenized_dataset=dataset,
            tokenizer=tokenizer,
            evaluate_metric="accuracy",
            num_train_epochs=5,
        )
        trainer.train()
        # Evaluate accuracy
        eval_results = trainer.evaluate()
        print(f"Evaluation accuracy: {eval_results['eval_accuracy']}, Sparsity: {sparsity}")
        pruned_accuracies[mode].append(eval_results['eval_accuracy'])

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier
/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier

Evaluation accuracy: 0.83476, Sparsity: 0.1

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier

Evaluation accuracy: 0.84216, Sparsity: 0.2

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier

Evaluation accuracy: 0.84164, Sparsity: 0.30000000000000004

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier

Evaluation accuracy: 0.84264, Sparsity: 0.4

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier

Evaluation accuracy: 0.84244, Sparsity: 0.5

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier

Evaluation accuracy: 0.8406, Sparsity: 0.6

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier

Evaluation accuracy: 0.84308, Sparsity: 0.7000000000000001

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier

Evaluation accuracy: 0.8414, Sparsity: 0.8

/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Evaluation accuracy: 0.84344, Sparsity: 0.9

INFO     Pruning module: bert_encoder_layer_0_attention_self_query
INFO     Pruning module: bert_encoder_layer_0_attention_self_key
INFO     Pruning module: bert_encoder_layer_0_attention_self_value
INFO     Pruning module: bert_encoder_layer_0_attention_output_dense
INFO     Pruning module: bert_encoder_layer_0_intermediate_dense
INFO     Pruning module: bert_encoder_layer_0_output_dense
INFO     Pruning module: bert_encoder_layer_1_attention_self_query
INFO     Pruning module: bert_encoder_layer_1_attention_self_key
INFO     Pruning module: bert_encoder_layer_1_attention_self_value
INFO     Pruning module: bert_encoder_layer_1_attention_output_dense
INFO     Pruning module: bert_encoder_layer_1_intermediate_dense
INFO     Pruning module: bert_encoder_layer_1_output_dense
INFO     Pruning module: bert_pooler_dense
INFO     Pruning module: classifier
/vol/bitbucket/rg1322/ELEC70109-Advanced-Deep-Learning-Systems/src/chop/tools/huggingface.py:157: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [ ]:
pruned_accuracies

NameError: name 'pruned_accuracies' is not defined